name: compile_and_test

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  build_and_test:
    name: Build & test on ${{ matrix.config.os }} with ${{ matrix.config.cc }} and ${{ matrix.config.cxx }}.
    runs-on: ${{ matrix.config.os }}
    env:
      build_directory: "cmake-build-debug"
    strategy:
      matrix:
        config:
          - {
            name: "Windows Latest - MSVC",
            os: windows-latest,
            cc: "cl", cxx: "cl",
            extra_cmake_flags: "-G Ninja",
          }
#          - {
#            name: "MacOS Latest - Clang",
#            os: macos-latest,
#            cc: "cc", cxx: "c++",
#            extra_cmake_flags: "-DCMAKE_OSX_ARCHITECTURES=x86_64 -DAPPLE=1" ,
#            build_options: "-j16",
#          }
#          - {
#            name: "Ubuntu Latest",
#            os: ubuntu-latest,
#            cc: "cc", cxx: "c++",
#          }

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Get current timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +'%s')"

      - name: Cache CMake
        id: cache-cmake
        uses: actions/cache@v3
        with:
          path: ${{ env.build_directory }}
          key:  ${{ runner.os }}-${{ env.build_directory }}-${{ steps.timestamp.outputs.timestamp }}
          restore-keys: |
            ${{ runner.os }}-${{ env.build_directory }}-

      - name: Setup MSVC
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1
        
      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
        run: pip install -r requirements.txt

      - name: CMake Configure (Debug)
        run: cmake -B ${{ env.build_directory }} -Wno-dev -DCMAKE_BUILD_TYPE=Debug -DGENKIML_BUILD_TESTS=ON -DGENKIML_BUILD_EXAMPLES=ON ${{ matrix.config.extra_cmake_flags }} -DCMAKE_C_COMPILER=${{ matrix.config.cc }} -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }}

      - name: CMake Build (Debug)
        run: cmake --build ${{ env.build_directory }} -- ${{ matrix.config.build_options }}

      - name: Run tests
        run: |
          cmake --build ${{ env.build_directory }} --target genkiml_tests
          ./${{ env.build_directory }}/tests/genkiml_tests
